name: Mirror Chocolatine
on:
  push:
    branches-ignore:
      - ga-ignore-
  pull_request:
    branches-ignore:
      - ga-ignore-

env:
  TEST: test

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Scan Repository
      run:  find . \( -name "#*" -o -name "*#" -o -name "*~" -o -name "*pain_au_chocolat*" -o -name "*.o" -o -name "*.a" -o -name "*.so" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" -o -path '*/tmp/*' \)
