name: Mirror Chocolatine
on:
  push:
    branches-ignore:
      - ga-ignore-
  pull_request:
    branches-ignore:
      - ga-ignore-

env:
  MIRROR_URL: "https://github.com/EpitechPromo2026/B-DOP-200-BDX-2-1-chocolatine-nolann.bougrainville"
  EXECUTABLES: "lib/my/libmy.a"

jobs:
  check_repository_cleanliness:
    name: "Check if the repository is clean and void of any unwanted files (temp, files, binary files, etc.)"
    runs-on: ubuntu-latest
    # container:
    #   image: epitechcontent/epitest-docker:latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Scan files
      run: |
        arr=($(find . \( -name "#*" -o -name "*#" -o -name "*~" \
        -o -name "*pain_au_chocolat*" -o -name "*.o" -o -name "*.a" \
        -o -name "*.so" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" \
         -o -path '*/tmp/*' \)))
        for i in ${arr[@]}; do echo "::error file=$i,line=1,endLine=1,title=Unwanted file detected::$i"; done
        exit 1
# if [[ $(find . -name '*.a') ]]; then
#   echo "::error line=1,endLine=1,title=En effet::je suis trop chaud"
#   exit 1
# fi
# echo: "Mama ça va être compliqué"