name: Mirror Chocolatine
on:
  push:
    branches:
      - '!ga-ignore-'
  pull_request:
    branches:
      - '!ga-ignore-'

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Scan Repository
      run: exit 1
