name: Mirror Chocolatine
on:
  push:
    branches-ignore:
      - ga-ignore-
  pull_request:
    branches-ignore:
      - ga-ignore-

env:
  MIRROR_URL: "https://github.com/EpitechPromo2026/B-DOP-200-BDX-2-1-chocolatine-nolann.bougrainville"
  EXECUTABLES: "lib/my/libmy.a"

jobs:
  check_repository_cleanliness:
    name: "Check this"
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Scan .a files
      run: |
        if [[ $(find . -name '*.a') ]]; then
          echo "::error line={1},endLine={1},title={En effet}::{je suis trop chaud}"
          exit 1
        fi
      # echo: "Mama ça va être compliqué"