name: Mirror Chocolatine
on:
  push:
    branches-ignore:
      - ga-ignore-
  pull_request:
    branches-ignore:
      - ga-ignore-

env:
  MIRROR_URL: "https://github.com/EpitechPromo2026/B-DOP-200-BDX-2-1-chocolatine-nolann.bougrainville"
  EXECUTABLES: "lib/my/libmy.a"

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Scan .a files
      run: ::set-output name=dota::echo ${#$(find . -name '*.a')}
      if: ${{ steps.dota.outputs.dota }}
      run: echo "::notice file={name},line={line},endLine={endLine},title={title}::{message}"
      # echo: "Mama ça va être compliqué"